# Meta Data for SEO

## Homepage
title = "libp2p"
titleSeparator = "-"
titleAddition = "libp2p Documentation Portal"
description = "libp2p is a modular system of protocols, specifications and libraries that enable the development of peer-to-peer network applications."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["libp2p_monochrome_horizontal.png"]
ogLocale = "en_US"
domainTLD = "docs.libp2p.io"
titleHome = "libp2p Documentation Portal"

## Twitter Cards
twitterSite = "@libp2p"
twitterCreator = "@protocollabs"

## JSON-LD
schemaType = "Organization"
schemaName = "libp2p"
schemaAuthor = "Protocol Labs"
schemaAuthorGitHub = "https://github.com/protocol/"
schemaLocale = "en-US"
schemaLogo = "libp2p_monochrome_vertical.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "libp2p_monochrome_horizontal.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/libp2p"
schemaLinkedIn = "https://www.linkedin.com/company/protocollabs/"
schemaGitHub = "https://github.com/libp2p/docs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Built with ❤️ from libp2p, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"


# Alert
alert = false
alertDismissable = true

# Edit Page
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/libp2p/docs"
docsRepoBranch = "master"
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
